version: "3.7"

services:
  #
  # mongo
  #
  mongodb:
    image: mvertes/alpine-mongo:3.6.5-0
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/db:/data/db
      - ./mongo/configdb:/data/configdb
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - "mongodb"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
