version: "3.7"

services:
  #
  # mongo
  #
  mongodb:
    image: mvertes/alpine-mongo:3.6.5-0
    restart: always
    ports:
      - "${PORT_MONGODB}:27017"
    volumes:
      - ./mongo/db:/data/db
      - ./mongo/configdb:/data/configdb
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "${PORT_MONGODB_EXPRESS}:8081"
    depends_on:
      - "mongodb"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
  #
  # memcached
  #
  memcached:
    image: memcached:alpine
    restart: always
    ports:
      - "${PORT_MEMCACHED}:11211"
    networks:
      main:
        aliases:
          - memcached
  #
  # postgres
  #
  postgres:
    image: postgres:alpine
    ports:
      - "${PORT_POSTGRES}:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
  pgweb:
    image: sosedoff/pgweb
    ports:
      - "${PORT_PGWEB}:8081"
    links:
      - postgres # my database container is called postgres, not db
    # environment:
    #   # format: postgres://user:password@host:port/db?sslmode=mode
    #   # TODO: なんだかしらんがdockerからだとつながらないため、以下のURLをブラウザから叩く
    #   - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
    depends_on:
      - postgres

networks:
  main:
