version: "3.7"

services:
  #
  # mongo
  #
  mongodb:
    image: mvertes/alpine-mongo:3.6.5-0
    restart: always
    ports:
      - "${PORT_MONGODB}:27017"
    volumes:
      - ./mongo/db:/data/db
      - ./mongo/configdb:/data/configdb
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "${PORT_MONGODB_EXPRESS}:8081"
    depends_on:
      - "mongodb"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
  #
  # memcached
  #
  memcached:
    image: memcached:alpine
    restart: always
    ports:
      - "${PORT_MEMCACHED}:11211"
    networks:
      main:
        aliases:
          - memcached

networks:
  main:
